name: CI
# This workflow is triggered on pushes to the repository.

on: 
  push:
    branches:
      - master
    pull_request:
      types: [closed]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Force xcode 11
      run: sudo xcode-select -switch /Applications/Xcode_11.4.app
    - name: Run tests
      run: xcodebuild -project 'Stormy.xcodeproj' -scheme 'Stormy' -destination 'platform=iOS Simulator,name=iPhone 8,OS=13.4' test
    - name: Build App
      run: xcodebuild -project 'Stormy.xcodeproj' -scheme 'Stormy' -destination 'generic/platform=iOS' -configuration Release build CODE_SIGNING_ALLOWED=NO

  dump:
    runs-on: macOS-latest
    steps:
      - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  weather:
    runs-on: ubuntu-latest
    env:
      location: 37.8267,-122.423
      lang: en
      units: us
      dark_sky_secret: ${{ secrets.dark_sky }}
    steps:
      - name: Current Weather
        run: curl -s --url https://api.forecast.io/forecast/$dark_sky_secret/$location?lang=$lang&units=$units

  pull_request_only:
    runs-on: macOS-latest
    if: github.event_name == 'pull_request'
    needs: build

    steps:
    - uses: actions/checkout@v1
    - name: Force xcode 11
      run: sudo xcode-select -switch /Applications/Xcode_11.4.app
    - name: Run tests
      run: xcodebuild -project 'Stormy.xcodeproj' -scheme 'Stormy' -destination 'platform=iOS Simulator,name=iPhone 8,OS=13.4' test
